### PR TITLE
check sys.modules in case of non-ImportError import exceptions

### LINKED ISSUE #118: Don't do try: except for imports, check sys modules first
You should check if the library is in `sys.modules` rather than try:excepting the imports. If the user has a `DataFrame` in their kernel, for example, then pandas will have already been imported. 

The issue with try:excepting arises when libraries like [tensorflow](https://github.com/lckr/jupyterlab-variableInspector/blob/master/src/inspectorscripts.ts#L44) are compiled with AVX, and run on machines without AVX. This will usually not raise an `ImportError`, but will instead cause a segfault leading to an infinite kernel restart loop. Again, if the user has a tf variable in their kernel, then tensorflow will have already imported fine and be in `sys.modules`. 
@vidartf @ceball

### PR DESCRIPTION
**Pull request by timkpaine**
fixes #118

### CODE REVIEW

File: src/inspectorscripts.ts [hunk 1]
```diff
@@ -25,29 +25,43 @@ _jupyterlab_variableinspector_nms = NamespaceMagics()
...
+
+    if 'tensorflow' in sys.modules or 'keras' in sys.modules:
+        try:
+            import tensorflow as tf
+            import keras.backend as K
+        except ImportError:
+            tf = None
 
 
 def _jupyterlab_variableinspector_getsizeof(x):
```
Comment (lckr) [inline src/inspectorscripts.ts]: Do we need to call `_check_imported()` for each subfunction? Shouldn't it be enough to call it once when the script is initialized?

Comment (timkpaine) [reply src/inspectorscripts.ts]: @lckr yes, otherwise it will continue to evaluate the module name as `None`

Comment (timkpaine) [reply src/inspectorscripts.ts]: @lckr you call it on each function so that once the user imports it, you update the module name to be correct e.g. before the user imports `tensorflow`, `tf=None`, but then once they do, `tf=tensorflow`

Comment (lckr) [reply src/inspectorscripts.ts]: Thanks but my point is that is should be enough to call `_check_imported()` only in the `def _jupyterlab_variableinspector_dict_list()` method which is executed each time the kernel updates and also calls all other methods.
Therefore we would save us the multiple executions of `_check_imported()` that are not really required, or do you see this differently?

Comment (timkpaine) [reply src/inspectorscripts.ts]: Sounds good so long as it's executed first, I wasn't sure what the code paths were
